### ISSUE TITLE
Translatable - field will not be updated if same value in different languages

### ISSUE THREAD

**Issue by kingschnulli** [doctrine-extensions/DoctrineExtensions#1014]
I have a translatable that won't update if the value of 2 languages is the same. Example

``` php
class Product implements Translatable{
      /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Gedmo\Translatable
     */
    protected $title;
}
```

Usage in a sf2 controller:

``` php
$em = $this->getDoctrine()->getManager();
$entity = new Product();
$entity->setTitle('shirt');
$em->persist($entity);
$em->flush(); //works

$entity->setTranslatableLocale('de_DE')
$entity->setTitle('shirt2');
$em->persist($entity); //works
$em->flush($entity);

$entity->setTItle('shirt'); 
$em->persist($entity); //fails
$em->flush($entity);
```

I think this is due to following line in 

https://github.com/l3pp4rd/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/TranslatableListener.php#L602

``` php
if (((is_null($content) && !$isInsert) || is_bool($content) || is_int($content) || (is_string($content) && strlen($content) > 0) || !empty($content)) && ($isInsert || !$transWrapper->getIdentifier() || /*isset($changeSet[$field])*/true)) {
```

I commented out the changeSet check and it works now - is this a bug or is this due to wrong usage?

**Comment by sfblaauw** [comment]
ping @Atlantic18/owners, any news?

**Comment by sgasser** [comment]
I made a ugly hack for getting this working: https://github.com/sgasser/DoctrineExtensions/commit/00a9d743b27a476594d361b11575885427ce629f

@l3pp4rd this is really a ugly hack. Any suggestions how to fix this better?
The primary problem is that $changeSet for this field is empty.

**Comment by l3pp4rd** [comment]
hi, @sgasser the reason why it is not implemented is because orm won't hit the listener at all if you change only a title field to the same value it was before (since there won't be any changeset for the entity at all). In such situations you can use a repository method **translate** which persists a translation record directly. I could not find a good way to manage this behavior, though it confuses users when they stumble on this

**Comment by sgasser** [comment]
@l3pp4rd it's not the same value it was before - it's the same value as in the default language...
I thinks this is a bug which has to be resolved...
Because we can never save the same value as the default language...

**Comment by l3pp4rd** [comment]
yes a default translation value to be exact, but it still has to be a value, since translated entity has to have a field which is being translated. I do not see a nice way how to handle it, even if we always force to persist default translation this field has to have some value stored in the database. If we change it to **unstranslated** or something similar - it will end up in the database, though in that case it would always trigger the changeset unless translation is the same. not sure whether this is a better solution to go for.

Also, this change may not be possible, because it can translate integers or other values. If you have a better idea, I'm open..

**Comment by sgasser** [comment]
@l3pp4rd any new hint how to fix this?

Is it correct using here the orm listener on the object because the change is in the translations table?

**Comment by l3pp4rd** [comment]
I do not think there is a way with current implementation, apart from using repository method. I explained the reason in previous method.

**Comment by redjanym** [comment]
Hope this will help anyone still having the issue. 
I found a workaround for it. Before setting the translated value via $entity->translate('locale') method you first need to manually set and change the default locale of the entity before persisting it. 
Example:

$entity->setDefaultLocale("en");
$entity->translate("en")->setTitle("English Title");

$entity->setDefaultLocale("sq");
$entity->translate("sq")->setTitle("Titull Shqip");

$entityManager->persist($entity);
$entity->mergeNewTranslations();
