### ISSUE TITLE
Entity was not found exception

### ISSUE THREAD

**Issue by driesvints** [doctrine-extensions/DoctrineExtensions#1127]
Scenario: I have two entities. Product & ProductGroup. Product has many to one relation to ProductGroup. I soft delete the ProductGroup. Then I try to call `getProductGroup` on a product which has a product group which was soft deleted.

Problem: instead of expected `null` result I get an "Message: Entity was not found." exception message.

``` php
$productGroupName = $product->getProductGroup() !== null ? $product->getProductGroup()->getName() : '';
```

Stacktrace:

```
#0 /vagrant/library/Proxies/__CG__BeatswitchStockProductGroup.php(208): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(Proxies\__CG__\Beatswitch\Stock\ProductGroup), 'getName', Array)
#1 /vagrant/library/Proxies/__CG__BeatswitchStockProductGroup.php(208): Closure->__invoke(Object(Proxies\__CG__\Beatswitch\Stock\ProductGroup), 'getName', Array)
#2 /vagrant/application/views/scripts/product/overview.phtml(29): Proxies\__CG__\Beatswitch\Stock\ProductGroup->getName()
#3 /vagrant/vendor/zendframework/zendframework1/library/Zend/View.php(108): include('/vagrant/applic...')
#4 /vagrant/vendor/zendframework/zendframework1/library/Zend/View/Abstract.php(888): Zend_View->_run('/vagrant/bootst...')
#5 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('product/overvie...')
#6 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('product/overvie...', NULL)
#7 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#8 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#9 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#10 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('overviewAction')
#11 /vagrant/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#12 /vagrant/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(101): Zend_Controller_Front->dispatch()
#13 /vagrant/vendor/zendframework/zendframework1/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#14 /vagrant/public/index.php(14): Zend_Application->run()
#15 {main}  
```

Any help is greatly appreciated because I'm really pulling my hair out on this one.

**Comment by prvijesh** [comment]
@driesvints  I'm facing the same issue. Is there any updates?

**Comment by driesvints** [comment]
@prvijesh I eventually stopped using this library. Sorry, can't be of more help :-/

**Comment by l3pp4rd** [comment]
the issue is trivial, I think it would be best to handle it custom. people also hook to presoftdelete event to cascade deletion, if we put this by default it may also trigger a bunch of issues. I would recommend to solve these problems by customizing the behavior of softdeleteable

**Comment by zaibi099** [comment]
The same issue occurred with me and it is because of proxies Doctrine2 was generating, not the case with `soft-deletable` though i'm using that. But in entities where this `soft-deleteable` wasn't implemented i was having the same issue. so what fixed for me is Adding `fetch="EAGER"` on Entities Annotations where relation was defined. like

```
/**
 * @var \ReisesparerAPIs\Entity\Vouchers
 *
 * @ORM\OneToOne(targetEntity="ReisesparerAPIs\Entity\Vouchers", inversedBy="couponOrder", fetch="EAGER")
 * @ORM\JoinColumns({
 *   @ORM\JoinColumn(name="voucher_id", referencedColumnName="id")
 * })
 */
private $voucher;
```

[Reference Link](https://stackoverflow.com/questions/26891658/what-is-the-difference-between-fetch-eager-and-fetch-lazy-in-doctrine)

**Comment by bkrnetic** [comment]
I've just came across this issue when working with ManyToMany relation, where pivot table that is used as a connection between the two doesn't implement soft deletable behaviour. Removing records from pivot table is not an option since I need them for potential backup (undeleting) of the entities.

Say you have entities `A`, `B` and `C` with the following relationship: `A` oneToMany `B` manyToOne `C`.

I have a logger service that logs all the actions done with entity `A`, as well as the ones on the other entities (in this case entity `C`) related to entity `A` . 

Say there is a field `name` of entity`C` that is changed and I want to add a record about it. I log the change as "Field `name` of entity `C` changed for entity `A`. In that case, if I soft deleted entity `A` previously, which kept the rows in a pivot table and I try to access some of its fields, I will not be able to do it and I will get the same error as the one in the OP.

The workaround here is to either write custom SQL query which returns non deleted entities only or disabling and reenabling `soft_deletable` filter like this:

```
if ($this->_em->getFilters()->isEnabled('soft_deletable')) {
    $this->_em->getFilters()->disable('soft_deletable');
}

// ... do what is neccessary

if (!$this->_em->getFilters()->isEnabled('soft_deletable')) {
    $this->_em->getFilters()->enable('soft_deletable');
}
```

I consider the first approach a better one, but sometimes the second one will be faster, both implementation and performance wise.
