### ISSUE TITLE
[MongoDB] [tree] [matherializedPath] Cannot use custom id as TreePathSource

### ISSUE THREAD

**Issue by karser** [doctrine-extensions/DoctrineExtensions#1167]
If i use @MongoDB\Id(strategy="NONE"), the type of field is not "id", it is "custom_id".
Please allow this type to use with TreePathSource
Need to add "custom_id" to array $validPathSourceTypes in Gedmo\Tree\Mapping\Validator

**Comment by stephaun** [comment]
I am having a somewhat similar issue, where I am using a custom Id generator:
```php
/*
* @ORM\Id
* @ORM\Column(type="string", length=255, options={"fixed":true, "collation":"utf8_bin"})
* @ORM\GeneratedValue(strategy="CUSTOM")
*/
protected $id;
```
However I cannot use the nested tree because the Level, Left, Right, and Root properties are being forced to integer-only with Gedmo\Tree\Mapping\Validator. 
Why is this? If I simply add 'string' into the ``` $validTypes ``` array everything seems to work fine. Anyone have suggestions/workarounds to this seemingly arbitrary restriction?
