### ISSUE TITLE
After the update 2.3.10, @Gedmo\TreeLevel is not updating anymore

### ISSUE THREAD

**Issue by tormit** [doctrine-extensions/DoctrineExtensions#1231]
I'm using closure tree strategy.

**Comment by stof** [comment]
Please provide more details about your issue. The current message does not give us any chance to understand what the issue could be

**Comment by tormit** [comment]
I'm sorry, it was probably false alarm. Might not be related to 2.3.10.

It seems that something has changed in the entity manager that caused this issue.
The scenario is that I needed to update/flush same entity twice because of my business logic. The second flush set the level NULL. When I did entity refresh between the operations, problem got solved. Some time ago it worked without refresh as well.

**Comment by Morgorth** [comment]
this is quite similar to the issue I have here:https://github.com/Atlantic18/DoctrineExtensions/issues/1216
This issue started after I updated Symfony to 2.5

**Comment by kr0hmy** [comment]
The issue is also present in 2.3.9.
I also worked around it using entity refresh.

I searched a little into it, and actually the TreeLevel is correctly set in DB and inside doctrine entity manager. But the entity is not updated back with the new value.
And when you re-flush the entity, your entity TreeLevel and the data in the entity manager does not match so doctrine update the value to null...
Or something close to this...

For a moment i thought it could come from my doctrine-commons version (Composer dependencies was resolving to 2.5.x-dev), but after fixing Doctrine version to 2.4.x-dev, i can still reproduce the issue.

**Comment by Morgorth** [comment]
hummf, I've had too many issues with this extension: I wrote my own recursion tree builder so I'm not using this anymore

**Comment by matigda** [comment]
Has anyone solved this? I'm currently strugling with nested set strategy and have the same issue.

**Comment by l3pp4rd** [comment]
how it can be reproduced? could you add a test case in the test suite?

**Comment by matigda** [comment]
I'll try to add it in a couple of days. But it's the most basic thing - when child node has parent and I want to set new parent that has higher nested level, child has assigned new parent but level doesn't change.

**Comment by l3pp4rd** [comment]
These actions are not supported. What you do when you want to move subfolder as a parent to current file folder? **A**: You make two actions. Doctrine extensions cannot perform two flush operations, because they are binding to a single transaction. This would be too complex to try to implement anyway. But the reasonable exception should be thrown, for nested set it is thrown, but close tree is contributed.
