### ISSUE TITLE
ORM entity log into a Mongo db

### ISSUE THREAD

**Issue by gnorby88** [doctrine-extensions/DoctrineExtensions#1406]
I want logging all changes on an ORM entity into a Mongo database. Is this possible?

**Comment by l3pp4rd** [comment]
fork and adapt https://github.com/DATA-DOG/DataDogAuditBundle to your needs, it tracks all changes to everything in database, just publish to mongo instead of the same database in this case. there are no general solutions for audit logging, you would need to customize to fit your business requirements

**Comment by gnorby88** [comment]
Ok. Thanks.

**Comment by ypereirareis** [comment]
Hi,

There is no solution to use the loggable extension to log into MongoDB (and documents) updates done on entities stored into Entities  ?

Thanks !!

**Comment by pro100coder** [comment]
Hi @ypereirareis  +1 
I want to write entity changes into mongo(or other doctrine support). It's solution for performance optimization
