### ISSUE TITLE
Fluent metadata driver support

### ISSUE THREAD

**Issue by guiwoda** [doctrine-extensions/DoctrineExtensions#1534]
Hi!

I'm one of the authors of [Fluent](https://github.com/laravel-doctrine/fluent), a metadata driver aimed at easing usage of Doctrine's mapping concepts in Laravel. It is framework-agnostic and fully tested and functional.

We've been adding support for your package on our end, and we'll be ready to tag it in a few days! But I was wondering: Would you be open for merging the `Gedmo\...\Fluent` extension driver (the ones that implement your `Driver` interface) in this repository? We're actually implementing all classes as `Gedmo\<extension>\Mapping\Driver\Fluent` because of how this extensions work, and maybe that code could belong in here instead of in our repo.

Moreover, we are extending ClassMetadata so that parsing is done only once, and metadata gets cached along with the rest of Doctrine's default metadata info. Don't know if you have any use for that in your current metadata implementations, but we'd be open to helping you implement that as well!

You can see our progress on integrating this to Fluent currently on the [extensions-support branch](https://github.com/laravel-doctrine/fluent/tree/extensions-support).

Cheers!

**Comment by l3pp4rd** [comment]
Hi @guiwoda this looks interesting, I have a few concerns though:

- php 5.5 whether to switch master and 2.5 releases to this requirement
- mongodb odm support (does **Fluent** handle ODM metadata?) even though, I see that ODM community and driver support is shrinking, but I still have to maintain it. In case if **Fluent** does not support ODM I doubt that it would be useful to implement it on **Fluent** too much effort and not as many users, would not advice to do it anyway.

As far as I understand **Fluent** extends ORM metadata and supports adding custom mapping information? This would surely be better to integrate since extensions reread mapping from drivers.

Note, that I will not change extensions much, only maintenance is on my mind for future releases of extensions, since I do not use PHP much these days. As a consequence, if you'd implement extension support on your end for ORM I think you won't need to struggle with changes from extension side.

**Comment by guiwoda** [comment]
hey @l3pp4rd!
We're planning on supporting ODM some day, but right now we don't. This wouldn't be a problem, as dependencies wouldn't neither, because the integration is between fluent + Gedmo. If you are choosing Fluent, then you must have php 5.5+, ORM 2.5+. Nothing changes on the Gedmo side.

ExtensibleClassMetadata and ExtensibleClassMetadataFactory may be better suited for a PR on ORM itself, as we could offer the ORM a way of extending all drivers. I'll ping the doctrine-dev channel to see what they think.

And if you're only doing maintenance, then maybe it's better we keep the code in our end, so we don't create an upstream dependency on you.


Cheers!

**Comment by l3pp4rd** [comment]
Yes probably I'll keep it in **todo** list for now, since it is tempting to have a generic solution for metadata mapping, but I need to maintain 2.5 ORM and ODM and php 5.4 requirement same as for these libraries. Probably when ORM 2.6 is released I'll have a peek at **Fluent** again.

Cheers, thanks for the reference ;)

**Comment by catalinbuletin** [comment]
Hi @l3pp4rd!

No support yet for the Fluent metadata driver? I'm guessing this is why I get this issue here:
[[Tree] - lft, rgt, root, lvl are all 0 after flush()](https://github.com/Atlantic18/DoctrineExtensions/issues/1891)

**Comment by l3pp4rd** [comment]
hi @catalinbuletin most likely, but you should inspect it to be sure, this issue is long time inactive, guess either users find easy workaround or they do not use it. due to such low demand I doubt that it could be ever integrated, maintaining a support for another third party is a high and risky commitment
