### ISSUE TITLE
Improvement using entity traits

### ISSUE THREAD

**Issue by enachesilviu** [doctrine-extensions/DoctrineExtensions#1558]
I'm getting this exception:

vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Mapping/Driver/Annotation.php line 90, method is "readExtendedMetadata"

[Gedmo\Exception\InvalidMappingException]
  Class must be annotated with Loggable annotation in order to track versioned fields in class - AppBundle\Entity\Label

Label has a "name" conveniently provided by a NameableEntity trait. This property is annotated with @Gedmo\Versioned. My feature request is to discard this annotation when the class using the trait is not using @Gedmo\Loggable annotation. Properties such as "name", "description", "owner" can be implemented via traits in order to reduce the amount of code throughout the entity namespace. My point is that property annotations - on traits - should be silently ignored when they are not needed by the entity class. Traits can be used for both reuse of code and reuse of configuration (by this, I mean annotations) at the same time, I want the configuration part in the traits to be optional in the semantics of the entity class.

I'm not really accustomed to the structure of this library to be able to contribute but I hope I managed to explain this properly and wish you consider taking a look at this.

**Comment by l3pp4rd** [comment]
Hi, in PHP you cannot import annotations in Trait implementation, it won't just work because of PHP internals. You must import annotations used by traits in the class it is used. This has nothing to do with extensions in general, if I understood the issue correctly, please post the entity examples if you cannot resolve the issue based on this comment..

**Comment by enachesilviu** [comment]
I can toggle the indexing of "name" property for FOSElasticaBundle by switching between

@Serializer\Exclude() and @Serializer\Expose() annotations on $name field. I can notice the change by retrieving the document from ElasticSearch using Get API, whether the field is present or not in the resulting document so it does work. This is merely an example on annotations usage, it might not work with the internals of DoctrineExtensions.

`<?php

namespace AppBundle\Entity\Traits;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Implements a "name" field on an entity
 */
trait NameableEntity
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=false, length=255, unique=true)
     *
     * @Serializer\Groups(groups={"elastica"})
     * @Serializer\Exclude()
     */
    protected $name;

    /**
     * @return string
     */
    public function __toString()
    {
        return (string)$this->name;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }
}
`

**Comment by l3pp4rd** [comment]
ah, I misunderstood the question initially. well, from your side of use case that makes sense, but if user forgets to add this annotation by mistake it would be confusing to understand why it is not working as expected. Not sure how many users would be happy to have this feature available, there were no requests for that before. If you for example use YML or XML mapping this change would also be confusing, because you control entity mapping directly, not in a trait. Somehow I do not think that this change makes sense especially for all mappings, only annotations in cases like yours.
