### ISSUE TITLE
[Translatable] Set the @Gedmo\locale property (after query)

### ISSUE THREAD

**Issue by lenybernard** [doctrine-extensions/DoctrineExtensions#1560]
Hello,

I noticed it's not possible for now to get the current locale for an entity we get (especially when forcing the locale with the Hint) because the @Gedmo\locale annotated property is not set during or after the run.
Do you think there is a way to set this property to be used like a virtual column actually ?
IMO this `locale` property bring an important information, the current entity translation locale, what do you think ?

**Comment by l3pp4rd** [comment]
yes, it could be set in this case, seems like an appropriate option.

**Comment by lenybernard** [comment]
ok, do you have any idea about the way you would like it to be done ?

**Comment by l3pp4rd** [comment]
It should be in few places:

- postload after skipOnLoad check, since this is handled by query based hydration
- [hydrator](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/Hydrator/ORM/ObjectHydrator.php#L36) should have [hint set with locale](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/Query/TreeWalker/TranslationWalker.php#L286) read it like in [this example](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php#L86) and set the locale field to all hydrated objects on hydration (override hydration result method) to loop over results.

Not sure if this is the best solution, but seems good enough, if you have other ideas I'm open
