### ISSUE TITLE
Translatable cannot translate a locale

### ISSUE THREAD

**Issue by binhle410** [doctrine-extensions/DoctrineExtensions#1590]
I have a default content set as "FOREWORD"
the translated locale is "INTRODUCTION".
If I try to translate INTRODUCTION into FOREWORD, the translatable won't work.
It only works when I change the default "FOREWORD" content into something else such as "OLD FOREWORD".

How do we fix this?

**Comment by l3pp4rd** [comment]
are you sure you are changing locale in translatable listener? debug your issues, translatable works as described in documentation.

**Comment by binhle410** [comment]
yes, I did, here is the case.
Creation: OK
--- original content: abc
--- translated content: abc
Modification: OK
--- original content: abc
--- translated content: abc->def
Modification: FAILED
--- original content: abc
--- translated content: def->abc

**Comment by l3pp4rd** [comment]
this is most probably the reason that orm does not detect a changeset, since original field is also **abc** this issue is known, and translatable does not get triggered. the only option for now is to use repository->translate method, which generates translation entity directly.

**Comment by jnugh** [comment]
How about updating `originalEntityData` when fetching the translated data?
Something like:
```php
$om->getUnitOfWork()->setOriginalEntityData($entity, array($field => $value));
```

**Comment by l3pp4rd** [comment]
@jnugh there may be another "wtf" when an user will have custom event listeners and on change it would show him a diff with some unexpected data as an old value - forced as originalData. because you would need to use some value which could not be possibly used by user in order to detect whether it was default or not.

Not sure whether that could be a better option to take, because it could introduce more issues for users using custom event listeners already.
