### ISSUE TITLE
BC break on updating 2.4.13 to 2.4.14

### ISSUE THREAD

**Issue by kiczort** [doctrine-extensions/DoctrineExtensions#1624]
Hi,

After updating to 2.4.14 I've got error:
`[Semantical Error] The annotation "@Gedmo\Mapping\Annotation\SortablePosition" in property TestBundle\Entity\Page::$position does not exist, or could not be auto-loaded.`

**Comment by Padam87** [comment]
@kiczort Looks like the 2.4.14 release has referenced the master branch, which is for 3.0 and contains a lot of BC breaks.

@l3pp4rd I took the liberty of deleting the release and the tag before more update problems occur.

**Comment by l3pp4rd** [comment]
hope composer will refresh the tag soon..

**Comment by stof** [comment]
@l3pp4rd you can force the removal of the version on Packagist. Otherwise, there will be some delay

**Comment by l3pp4rd** [comment]
I think now it is OK. isn't it? I've checked packagist seems like it points to right commit

**Comment by spyral** [comment]
Had the same, went back to 2.3.13 for now. Hopefully packagist updates soon.

**Comment by stof** [comment]
@l3pp4rd you should have recreated it as 2.4.15 instead. Due to the immutable nature of git tags, anyone having fetched the repo with the wrong tag in it will keep using the old tag until they delete their local tag and then refetch it (same for forks btw).
Packagist is fine, because Packagist does not keep a local clone of the git repo to perform updates and then gives the commit reference to composer. But anyone using a VCS repo directly and forcing composer to skip the github API (either through explicit choice or because of being rate-limited) will also face the issue (until they clear their composer cache to make it clone the repo again).

In practice, deleting a git tag is already hard, but modifying it is a rod to hell.

**Comment by l3pp4rd** [comment]
added 2.4.15 to be sure, thanks. would be good to find any maintainers. currently I haven't worked with extensions and PHP over a year now :)

**Comment by phansys** [comment]
Closing this issue as the problem was resolved.
