### ISSUE TITLE
[Timestampable] on change of relation in join table

### ISSUE THREAD

**Issue by mikaint** [doctrine-extensions/DoctrineExtensions#1654]
What's the correct set up for updating timestamp when deleting a relationship on a join table?

```
class Contact {

    /**
     * @var \DateTime $listUpdated
     *
     * @Gedmo\Timestampable(on="change", field="lists")
     * @ORM\Column(type="datetime")
     */
    private $listUpdated;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Lists", inversedBy="contacts", cascade={"persist"})
     * @ORM\JoinTable(name="contact_list",
     *      joinColumns={@ORM\JoinColumn(name="contact_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="list_id", referencedColumnName="id")}
     *      )
     */
    private $lists;

```

**Comment by l3pp4rd** [comment]
I do not think timestampable can be triggered when the many to many relation changes. because the **Contact** table does not change and the change is only applied to the other table - many to many association one. I do not think it would be a simple task to support this, since all objects in such case would need to be analyzed having relation with the watched timestampable object.
