### ISSUE TITLE
[Tree] Improve performance of inserting many items at a time into a tree (nested set)

### ISSUE THREAD

**Issue by zimmermanj42** [doctrine-extensions/DoctrineExtensions#1773]
When inserting a large amount of records, performance on the nested set extensions pretty much tanks.  Understandably, storing large trees inside SQL is going to prove difficult.

I've tried approaching bulk processing like Doctrine suggests, getting a "batch" of objects persisted, then flushing and assembling another batch.  This make for a speedy initial insert, but then it appears that almost for each inserted record, the nested tree code kicks in and runs multiple queries per each item inserted.  What I see a lot of time being spent on is updating things like the right and left values for the tree traversal.

I'm not seeing any documentation that shows how to best handle large inserts.  It's possible that it just is not suggested and the library is not build to handle such use cases.

Is there any way to improve the performance of large inserts?  These large inserts can be governed by a little bit of criteria too (for example, we are adding a whole new section of a tree, we are not adding these large amounts of items randomly in multiple areas of an existing tree).

**Comment by zimmermanj42** [comment]
I guess as an example of what I am thinking about, is it possible to set the tree fields via code and just insert them without triggering the tree extensions.

For example, we do a heavy amount of processing to these items before they go into the system.  Using known information and the structure of the data, we can probably pre-set the level, left, and right values manually and thus don't need to run individual queries to set this information.

If this tree gets inserted as a "sub tree" of another, we may need to run some bulk queries to update the level, left, and right values of other affected nodes via the newly inserted records, but even these would only be a handful of queries I think compared to the hundreds upon hundreds that are currently being run by fixing all the items individually.

**Comment by l3pp4rd** [comment]
Hi, extensions are not simple and made not having performance oriented architecture. They are made for easy usage and rapid development. If at some point you need better performance, your best option is to first of all not to use ORM, because everything around it is slow. Another option:

- is to read about [nested set trees](https://en.wikipedia.org/wiki/Nested_set_model) it is really simple
- build your nested set tree in memory (with correct lft rgt values)
- then insert all your records using DBAL (for even better performance).

It just would not be wise to even try to provide something like that in extension library, it always boils down to something custom.

If there is not enough memory (means you are persisting other tree node fields with huge data related, nullify these and update later).

In general, I should not be answering these kind of questions here, use stackoverflow if you cannot find a solution to such problem.
