### ISSUE TITLE
[Sluggable] - prefix/suffix format (random generated string)

### ISSUE THREAD

**Issue by StanislavUngr** [doctrine-extensions/DoctrineExtensions#1971]
Hello guys. Im currently working on project where we would like to have user pages slugs like following:

`firstname-lastname-ABCDEF`
`firstname-lastname-YoJ12a`
`firstname-lastname-WHATEVER_RANDOM`

Current config:

```
/**
     * @var string
     * @ORM\Column(type="string", unique=true)
     * @Gedmo\Slug(fields={"firstname", "lastname"}, unique=true, updatable=false)
     */
    protected $slug;
```

So basically for every duplicate firstname and lastname there would be randomly generated suffix - string of X chars. 
The problem is standard behavior creates suffix with incrementing number starting from 1 - that is obviously very dangerous for many reasons.

I know there is an option to set prefix/suffix statically but thats inusable for our use case... 

Have any of you solved similar request so far?

**Comment by cybernet** [comment]
+1. i’m interested 
any news on this ?

**Comment by AkenRoberts** [comment]
Hello, and sorry for the lack of attention.

It's unlikely that this feature will make it into the current Doctrine Extensions, just due to lack of maintenance and modernization efforts here.

You may be able to add the functionality yourself using [slug handlers](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/sluggable.md#using-slug-handlers).

Otherwise, I've added it as a feature request to the new Extensions library we hope to create as a modern replacement for the current standards. Follow over there if you're interested!
