### ISSUE TITLE
[Tree] MaterializedPathRepositoryTrait

### ISSUE THREAD

**Issue by michaelgracious** [doctrine-extensions/DoctrineExtensions#2047]
So reading the documentation it says there's a trait called `MaterializedPathRepositoryTrait `. But this trait does not exist! Looking further it says you can also extend `MaterializedPathRepository`. Now, when i do this i get an error telling me i should map my repository ( `The class 'App\\Repository\\CategoryRepository' was not found in the chain configured namespaces App\\Entity, Gedmo\\Tree\\Entity` ). Why does it want me to register my repo as a mapping?

Where did this trait disappear to? why is it telling me to map my repo? how do i properly implement this?

edit:
I don't know what happened, but this commit added the trait https://github.com/Atlantic18/DoctrineExtensions/commit/2a2671317d1334f8988fbea927e666de84ce4753 but i can't for the live of me find where it was removed, by who or why.

**Comment by thePhrenologist** [comment]
Yeah, pretty sure it's gone. https://github.com/Atlantic18/DoctrineExtensions/tree/archive/master-2019-03-17 still has it

**Comment by AkenRoberts** [comment]
It was introduced in PR #1496, which targeted an old `master` branch and an old attempt at either a 2.5 or 3.0 release of Doctrine Extensions.

Since then, the long-time maintainer has moved on, the work-in-progress `master` branch got kind of orphaned The documentation on http://atlantic18.github.io is based on that branch and is woefully out of date. I apologize for the confusion.

I'm in the process of trying to unify where things are at _currently_, so that we can make proper updates and possibly make features like this trait available again.

I don't have an answer for your repository issue at the moment. I will leave this open and try to return to it. Apologies for not being more helpful at this time.

**Comment by emovere** [comment]
Please reintroduce the NestedTreeRepositoryTrait! @AkenRoberts

**Comment by AkenRoberts** [comment]
@emovere I definitely want to. Always open to PRs if you'd like to help contribute it!

**Comment by jmontoyaa** [comment]
I added a PR #2208
