### ISSUE TITLE
[Tree]❓Is it impossible to add a custom columns to getNodesHierarchyQueryBuilder()?

### ISSUE THREAD

**Issue by emovere** [doctrine-extensions/DoctrineExtensions#2093]
I've build a working custom getChildrenHierachy() function:

```
    public function getChildrenHierachyByCategoryIDs($categoryIDs)
    {
        $qb = $this->getNodesHierarchyQueryBuilder();
            $qb->andWhere('node.id in (:categoryIDs)')
            ->setParameter('categoryIDs', $categoryIDs)
        ;

        $aComponents = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        return $this->buildTreeArray($aComponents);
    }
```

Now I want to add a custom column to the result:
```
    public function getChildrenHierachyByCategoryIDs($categoryIDs, $highlightCategories)
    {
        $qb = $this->getNodesHierarchyQueryBuilder();
        $qb->addSelect('CASE WHEN(node.id = 5) THEN 1 ELSE 0 END') // 5 = test value
            ->andWhere('node.id in (:categoryIDs)')
            ->setParameter('categoryIDs', $categoryIDs)
        ;

        $aComponents = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);

        return $this->buildTreeArray($aComponents);
    }
```

The runnable query itself (that Symfony is generating) is working perfectly!

But I get an error from `return $this->buildTreeArray($aComponents);` with the message:
> Notice: Undefined index: level

(Full message:
Uncaught PHP Exception ErrorException: "Notice: Undefined index: level" at /PROJECT/vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/RepositoryUtils.php line 146)

**Is it impossible to add custom data to the getNodesHierarchyQueryBuilder()?**

**Comment by AkenRoberts** [comment]
I _think_ the issue is related to you not aliasing your statement result. (Apologies for the lack of time to try and reproduce.) Your `$aComponents` items should each have an index with the name of the column you defined as the `TreeLevel` (usually it's `level` or `lvl` -- in your case it appears to be `level`).

Maybe you can confirm that this index exists in your items in the working query, and then doesn't when adding in the new statement?

And to fix, you can try adding `as my_result` (or whatever you want to name that "column") after the `END` part of your statement to assign it a name to use in the result.

And since this is just a guess, please update if that isn't the case. Any more stack traces or data dumps you can add will help.
