### ISSUE TITLE
Get child nodes by id with all parents not possible (NestedTreeRepository)?

### ISSUE THREAD

**Issue by emovere** [doctrine-extensions/DoctrineExtensions#2095]
**Goal:**

I have a category entity.
Every category can have subcategories.

Now I want to get specific category nodes by id with *all* its parents

**My current solution (custom repository function):**

    public function getChildrenHierarchyByCategoryIDs($categoryIDsArray)
    {
        $qb = $this->getNodesHierarchyQueryBuilder();
        $qb->andWhere('node.id in (:categoryIDs)')
           ->setParameter('categoryIDs', $categoryIDsArray)
            ->orWhere('node.id in (:rootNodes)') // "Workaround", get all available root nodes (1st level only) manually, because I don't know how to get them by children's parentID (node.parent) "automatically" (with second level etc.)
            ->setParameter('rootNodes', $this->getRootNodes())
        ;
    
        $aComponents = $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    
        return $this->buildTreeArray($aComponents);
    }

**Question:**

How can I get the parents (of all nodes found by id) automatically, instead of fetching every possible parent manually by id (See "Workaround" in code)?

I can't find any solution..

I think it should be something like: `->orWhere('node.id in (node.parent)')` which is not working. ([Syntax Error] line 0, col 89: Error: Expected Literal, got 'node')

Thanks in advance for taking your time!

**Comment by Guite** [comment]
Do you maybe need the `getPath()` method?

Example: https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#using-repository-functions

**Comment by emovere** [comment]
Thank you for your help @Guite (Danke :))! 

While this seems to do what I want (get the full path / all parents), this doesnt seem to work in conjunction with my use case.

**My (not working) result:**
```
    public function getChildrenHierarchyByCategoryIDs($categoryIDsArray/*, $highlightCategories*/)
    {
        $qb = $this->getNodesHierarchyQueryBuilder();

        $qb->andWhere('node.id in (:categoryIDs)')
            ->setParameter('categoryIDs', $categoryIDsArray)
        ;

        $categoriesAsObject = $qb->getQuery()->getResult();
        $categoriesAsArray = $qb->getQuery()->getResult(AbstractQuery::HYDRATE_ARRAY);

        $parentCategoriesAsArray = array();
        foreach ($categoriesAsArray as $key => $category) {
            $parentCategoriesAsArray[] = $this->getPath($categoriesAsObject[$key]);
        }

        return $this->buildTreeArray(array_merge($parentCategoriesAsArray, $categoriesAsArray));
    }
```

**Error:**
Notice: Undefined index: level

What I need is a "getNodesHierarchyWithParentsQueryBuilder()" or something like "getNodesHoerarchyQueryBuilder(null, false, array('with_parents'=>true))".

Anyway, I've found:
```
        ->orWhere('node.id in (:rootNodes)') // "Workaround", get all available root nodes (1st level only) manually, because I don't know how to get them by children's parentID (node.parent) "automatically" (with second level etc.)
        ->setParameter('rootNodes', $this->getRootNodes())
```

Which is not perfect (as it only gets 1st level parent of EVERY category (not only the ones with the provided IDs), but I can live with that for now.

If anybody does have a better solution, I would highly appreciate it!

**Comment by AkenRoberts** [comment]
No real work-around available built in to Doctrine Extensions currently.

With nested sets, you find the parent hierarchy by using the left and right values of the set. That's why it's easy to find all of the parents for a node, because you already have the node's position in the tree. What's hard about what you're looking for is you'd need to know the left and right values of every category you're trying to fetch.

So you either need to fetch every category _first_, and then add their left and right details to the query build (see `getPathQueryBuilder` for an example), OR your query has to find these values using some sort of inner join or sub query if you only have the category IDs to start with.

I'm strapped for time to write something now, but that should at least give you an idea of how it works and what you need to do. Ping if I can help any more!
