### ISSUE TITLE
SoftDeletable causes removal of entites with onDelete="CASCADE" when parent has orphanRemoval

### ISSUE THREAD

**Issue by pkly** [doctrine-extensions/DoctrineExtensions#2175]
As in title, when you have an entity like:
```php
class Bar {
    // doctrine fields

    /**
     *  @ORM\ManyToOne(targetEntity=Foo::class, invertedBy="bars")
     *  @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $foo;
}

class Foo implements SoftDeletable {
    use SoftDeletableEntity;

    // doctrine fields

    /**
     * @ORM\OneToMany(targetEntity=Bar::class, mappedBy="foo", orphanRemoval=true)
     */
    private $bars;
}
```

// assuming $foo is an entity with multiple $bars
$em->remove($foo);
$em->flush(); // causes DELETE bar where foo_id = $foo->id

**Comment by AkenRoberts** [comment]
That is the intended behavior, though I understand how it may be confusing.

Doctrine is proceeding with the `remove()` command as called. Extensions will see that `Foo` is to be soft deleted and mark it as such. After it does, Doctrine itself will continue to process your remove command. Since you've said to cascade delete any orphans, and those orphans are not marked as soft delete themselves, they are removed normally.

You should add the SoftDeletable tags to your `Bar` classes as well if you don't want them fully removed.
