### ISSUE TITLE
Fixing corrupt tree (help needed)

### ISSUE THREAD

**Issue by olia-bn** [doctrine-extensions/DoctrineExtensions#2229]
I have a corrupt tree in my project.
How would I go around fixing the values?

**Comment by Padam87** [comment]
I have had a good experience with the recover method of the repository.
https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Tree/Entity/Repository/NestedTreeRepository.php#L813

(Also some general advice: bulk modifying the tree - eg in a loop can lead to this, because the way the lib works. Flush after every change, always trigger the updates)

**Comment by frizquierdo** [comment]
what are the conditions that can cause the tree to become corrupted!?
