### ISSUE TITLE
Closure metadata doesn't work with doctrine/persistence 2.2

### ISSUE THREAD

**Issue by hlecorche** [doctrine-extensions/DoctrineExtensions#2240]
Since `doctrine/persistence` 2.2.0, the `Gedmo\Tree\Strategy\ORM\Closure::processMetadataLoad` method does not work anymore :
* associations are not created
* indexes are not created

Tested with Symfony and doctrine-extensions 3.1.0  :
* Works in a dev environment. But not in a production environment
* Works only with  `doctrine/persistence` < 2.2.0

doctrine-extensions issue or Symfony issue ?

I think there is a link with #2236

**Comment by franmomu** [comment]
Thanks for reporting! Sorry, it has been a while since it was reported. 

Since there are some problems with this, we decided that it's better if the user adds the `ancestor` and `descendant` mappings manually: https://github.com/doctrine-extensions/DoctrineExtensions/blob/13dd920b1c6a5f29f92aef383f68e40913431c6a/doc/tree.md#closure-table

I'm closing this issue, but feel free to re-open if that doesn't fix your issue.
