### ISSUE TITLE
Possibly wrong typehint on UploadedFileInfo

### ISSUE THREAD

**Issue by mmarton** [doctrine-extensions/DoctrineExtensions#2413]
The other side of issue https://github.com/antishov/StofDoctrineExtensionsBundle/issues/32

Here https://github.com/doctrine-extensions/DoctrineExtensions/commit/907cd6e11f933ef03093220b93bb48e1b0c25484 FileInfoInterface got some new typehints with the latest release, and I think that the getSize method should return int (or ?int) instead of string|null.

In the docs the interface is used with $_FILES global (https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/uploadable.md#usage) which has a data type of int at the size key.

```php
array(1) {
     ["file"]=> array(5) {
         ["name"]=> string(10) "138728.jpg"
         ["type"]=> string(10) "image/jpeg"
         ["tmp_name"]=> string(14) "/tmp/php1FHOKM"
         ["error"]=> int(0)
         ["size"]=> int(504984)
     }
 } 
```

**Comment by franmomu** [comment]
Hi @mmarton, thanks for reporting!

This is interesting, I added `string|null` following:

https://github.com/doctrine-extensions/DoctrineExtensions/blob/a9fd83ad6e908e7180a719f174ded0b27aec2556/tests/Gedmo/Uploadable/UploadableEntityTest.php#L155

because when using 

```php
    #[ORM\Column(name: 'size', type: Types::DECIMAL)]
    #[Gedmo\UploadableFileSize]
    private $size;
```

`$size` has `decimal` type which means that [doctrine maps it as a `string|null`](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#decimal).

Given that, it's true that `FileInfoInterface::getSize()` shouldn't be coupled with the mapping, so I guess the `UploadableListener` should be in charge of parsing the result of `FileInfoInterface::getSize()` into the proper mapping type.

I'm not sure if I can take a look at this today, feel free to open a PR!
