### ISSUE TITLE
doctrine/persistence v3 is not allowed

### ISSUE THREAD

**Issue by garak** [doctrine-extensions/DoctrineExtensions#2450]
This repository is restricting `doctrine/persistence` to version 2.
Unless some changes introduced in v3 are blocking, the new version should be allowed as well.

**Comment by mbabker** [comment]
#2448 points out one blocker.  It looks like #2373 gave a way to fix it in downstream applications (and https://github.com/stof/StofDoctrineExtensionsBundle/pull/436 exists to help users of that Symfony bundle apply it), but the two places still calling that deprecated `Doctrine\Persistence\Mapping\AbstractMetadata::getCacheDriver()` method still need some kind of conditional logic to not fail hard with 3.0 installed.

It looks like https://github.com/doctrine/persistence/blob/3.0.x/UPGRADE.md#bc-break-removed-lifecycleeventargsgetentity could potentially be an issue, hard to say on a quick scan though because of how much dynamic code is involved in pushing the event args object through to the adapters.

Off hand, I don't know if there's anything in this package supporting short namespace aliases, but that's gone too - https://github.com/doctrine/persistence/blob/3.0.x/UPGRADE.md#bc-break-removed-support-for-short-namespace-aliases

**Comment by Romaixn** [comment]
+1 It would be very cool if V3 was supported for the package to work under Symfony 6 🎉

**Comment by mbabker** [comment]
> +1 It would be very cool if V3 was supported for the package to work under Symfony 6

This package will work fine with Symfony 6 (all the Symfony components that integrate with Doctrine support 2.x or 3.x for the Persistence package).  You'll need to ensure `doctrine/persistence` is locked to the 2.x branch in your application until #2454 is merged and a new release is published.

**Comment by franmomu** [comment]
I would be nice if people could try it before making a release using the `main` branch in their projects:

`"gedmo/doctrine-extensions": "dev-main"`
