### ISSUE TITLE
Gedmo\Tool\ORM\Walker\SqlWalkerCompat does not comply with psr-4 autoloading standard?

### ISSUE THREAD

**Issue by ovgray** [doctrine-extensions/DoctrineExtensions#2824]
When I upgraded from v3.15.0 to v3.16.0 and ran 

 composer install --no-dev --optimize-autoloader

I got the following:

Generating optimized autoload files
Class Gedmo\Tool\ORM\Walker\SqlWalkerCompat located in ./vendor/gedmo/doctrine-extensions/src/Tool/ORM/Walker/orm-2.php does not comply with psr-4 autoloading standard. Skipping.
Class Gedmo\Tool\ORM\Walker\SqlWalkerCompat located in ./vendor/gedmo/doctrine-extensions/src/Tool/ORM/Walker/orm-3.php does not comply with psr-4 autoloading standard. Skipping.

Is this a problem?

**Comment by mbabker** [comment]
It shouldn't be as those files are conditionally included from the correct PSR-4 file [here](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/src/Tool/ORM/Walker/SqlWalkerCompat.php) as part of the ORM compat layer.

Short of putting those files outside an autoloaded path, I don't think this is easily fixed with the way Composer crawls the filesystem to generate the optimized autoloader.

**Comment by wokenlex** [comment]
I've got It too, it's destroyed the production build on the basic "composer u".

**Comment by Chris53897** [comment]
@wokenlex `composer u` ?
What exactly is not working?

**Comment by mbabker** [comment]
Please explain how it has "destroyed the production build".  To my knowledge, these are just warnings that Composer will print when generating an optimized autoloader and would not actually fail any kind of update.

**Comment by wokenlex** [comment]
```

Fatal Error: Trait "Gedmo\Tool\ORM\Walker\SqlWalkerCompat" not found

{
    "class": "Symfony\\Component\\ErrorHandler\\Error\\FatalError",
    "message": "Error: Trait \"Gedmo\\Tool\\ORM\\Walker\\SqlWalkerCompat\" not found",
    "code": 0,
    "file": "/web/project/application/vendor/gedmo/doctrine-extensions/src/Translatable/Query/TreeWalker/TranslationWalker.php:57"
}
```

**Comment by mbabker** [comment]
Huh, well TIL a couple of things about PHP and Composer's optimized autoloader.  #2830 looks like it should fix that.

**Comment by wokenlex** [comment]
That's… was in the first page of the Symfony documentation about "how to publish on production" last 5 years, at least :-)

**Comment by mbabker** [comment]
I didn't realize traits could use traits, which is why the file that was supposed to be the right PSR-4 trait just had a couple of require statements originally, or that Composer would skip that specific file when dumping the optimized autoloader because of that.  Just a bunch of small little things that I admittedly didn't think to test when coming up with that all 😅

**Comment by ovgray** [comment]
I’m grateful for all the work that you have done. I’m sure the others are too. On Jun 25, 2024, at 10:15 AM, Michael Babker ***@***.***> wrote:﻿
I didn't realize traits could use traits, which is why the file that was supposed to be the right PSR-4 trait just had a couple of require statements originally, or that Composer would skip that specific file when dumping the optimized autoloader because of that.  Just a bunch of small little things that I admittedly didn't think to test when coming up with that all 😅
