### ISSUE TITLE
Performances of the translatable extension

### ISSUE THREAD

**Issue by stof** [doctrine-extensions/DoctrineExtensions#29]
The performances of the Translatable extension should be optimized when loading a collection. 
Generating my page uses currently 24 requests and 20 of them are done by the extension to load the translations for the loaded collection.

Considered features:
1. translation collection persistence
2. overrided persister to transform **find** requests and collection loads into translated, without issuing additional query
3. build a query walker which could be attached to any ORM query and autojoin translations without issuing additional queries.

**1, 3** will require personalized translation entity, with a composite constraint.

**Comment by Cedoriku** [comment]
Hi there,
I just wanted to submit a major issue I have and cannot solve with this new Translatable feature talked about here, allowing us to get the translated attribute directly joined in the query, and hydrated objects. (HINT_CUSTOM_OUTPUT_WALKER, HINT_TRANSLATABLE_LOCALE..).

Using this, a same query sometimes returns me only one or two results instead of the full result set, when I'm not in the default locale (and so using this feature).
This only happens on the production server, running under Linux, and can't be reproduced in my local WAMP server environment, neither in dev or prod environment.

I work with SQL server, and this could be coming from doctrine SQL server pilots, which could handle queries differently on windows and on Linux..

I think the issue happens during Doctrine Objects hydration, as I get the correct full result set when using getArrayResult() function..

Here is my thread in stackoverflow about this: http://stackoverflow.com/q/33544302/2707018

I know this might not be the right place for me to ask, but I really don't see how to solve this.

Thank you for your help.

@l3pp4rd @stof

**Comment by l3pp4rd** [comment]
hi @Cedoriku this looks like a complicated issue. What may be different in production is query caching. And in doctrine query result cache keys are built based on query hints also. So if you have a global locale changing, you should make a hint of locale to query too. Also, if you have a fallback option changes, you should make that as a hint too.

I doubt that it has something to do with **Windows** or **Linux** environment differences, most probably it is a cache related issue. Try to disable query result caches and see whether you get the same problem in production.

**Comment by Cedoriku** [comment]
@l3pp4rd  YOU ROCK! ! !
You definitely made my day! 

This was effectively a query cache issue.
Setting the query cache to false solves it.

So the solution to my problem was:

$query->->useQueryCache(false);

However I do not know what I really do by doing this. 
What do I loose by bypassing Doctrine Query cache?
Doesn't it affect the app's performance too much?

If you please I'm gonna answer my own question on the Stackoverflow thread to indicate the solution.
Maybe I could quote you if you please if I know your Stackoverflow pseudo?

Thank you very much.

**Comment by l3pp4rd** [comment]
Its http://stackoverflow.com/users/186355/gediminas. but you can just answer to yourself. disabling query cache is one side of the coin, another is why the query cache produced bad result. You should try to figure that out, since caching is useful and I would recommend to use it. So try to debug:

- the query cache key for your query.
- how does it change or not when your query state changes.

Because it is possible that you may experience the same issue again at another query.

**Comment by Cedoriku** [comment]
Thank you for these advices. I will, but I am not so familiar with cache issues, and don't really know how to debug this, so if you have any advice on how to do it, I'd be glad.
how (where?) do I find the query cache keys?
I will try by myself meanwhile.
Thank you.
