### ISSUE TITLE
[sortable] removing entities causes DQL error

### ISSUE THREAD

**Issue by Gamesh** [doctrine-extensions/DoctrineExtensions#370]
When removing entities from sortable crashes, in sortableListener at line 328 with invalid SQL:

``` sql
UPDATE SCMS\Entity\NewsArticlePhoto n SET n.position = n.position - 1 WHERE n.position >=  AND n.news_article = :val___0
```

``` php
array (size=3)
  'start' => null
  'stop' => int -1
  'delta' => int -1
```

tested on v2.3

**Comment by kminh** [comment]
I'm also having this issue, but my position column is not NULL (doesn't it by default have `nullable = false`?). This is my setup:

Question Entity:
```php
<?php

namespace Genj\FaqBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Question
 *
 * @ORM\MappedSuperclass
 * @ORM\Entity(repositoryClass="Genj\FaqBundle\Entity\QuestionRepository")
 * @ORM\Table(name="genj_faq_question")
 *
 * @package Genj\FaqBundle\Entity
 */
class Question
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @Gedmo\SortableGroup
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="questions", cascade={"all"})
     * @ORM\OrderBy({"rank" = "asc"})
     */
    protected $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $headline;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    protected $body;

    /**
     * @Gedmo\SortablePosition
     * @ORM\Column(name="rank", type="integer")
     */
    protected $rank;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    protected $updatedAt;

    /**
     * @Gedmo\Slug(fields={"headline"}, updatable=false)
     * @ORM\Column(type="string", length=50, nullable=false)
     */
    protected $slug;
    ...
}
```

and my Category Entity:

```php
<?php

namespace Genj\FaqBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Category
 *
 * @ORM\MappedSuperclass
 * @ORM\Entity(repositoryClass="Genj\FaqBundle\Entity\CategoryRepository")
 * @ORM\Table(
 *     name="genj_faq_category",
 *     indexes={@ORM\Index(name="is_active_idx", columns={"is_active"})}
 * )
 *
 * @package Genj\FaqBundle\Entity
 */
class Category
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="Question", mappedBy="category")
     */
    protected $questions;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $headline;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $body;

    /**
     * @Gedmo\SortablePosition
     * @ORM\Column(name="rank", type="integer")
     */
    protected $rank;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    protected $isActive;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated_at", type="datetime")
     */
    protected $updatedAt;

    /**
     * @Gedmo\Slug(fields={"headline"}, updatable=false)
     * @ORM\Column(type="string", length=50, nullable=false)
     */
    protected $slug;
    ...
}
```

Deleting a Question will result in: `[Syntax Error] line 0, col -1: Error: Expected Literal, got end of string. ` and the guilty DQL is `[1/2] QueryException: UPDATE Genj\FaqBundle\Entity\Category n SET n.rank = n.rank - 1 WHERE n.rank >= `

**Comment by l3pp4rd** [comment]
there were few updates regarding that, is it still relevant if you test it in master?

**Comment by kminh** [comment]
@l3pp4rd can I test again with latest stable version or the fix is only available in master?

**Comment by l3pp4rd** [comment]
it should be released, but not sure whether it was fixed or not.. would need a test case

**Comment by Viburnum** [comment]
I get the same issue, when I delete all sortable items in a sortable group. Using version 2.4.6

**Comment by l3pp4rd** [comment]
well it is complex to replicate, if you could create a test case in [group test](https://github.com/Atlantic18/DoctrineExtensions/blob/master/tests/Gedmo/Sortable/SortableGroupTest.php) or separate. to run test `./bin/phpunit -c tests tests/Gedmo/Sortable/SortableGroupTest.php` that would be very helpful

**Comment by ksn135** [comment]
same error, QueryException: UPDATE ContractFile n SET n.position = n.position + 2 WHERE **n.position >= nul**

**Comment by Padam87** [comment]
@kminh @Viburnum @ksn135 Please post a stack trace (since no one is willing to create a failing test), and I will fix it during the week.

**Comment by Padam87** [comment]
Also, it is very important that you don't have nulls in your database, as @Gamesh mentioned way back when the issue was reported.

**Comment by ksn135** [comment]
@Padam87 well, I made a hot fix thats works for me (see #1544 )

**Comment by Padam87** [comment]
This is not enough unfortunately. If the position index is null, when it shouldn't be, it could lead to other bugs. Please add a failing test, or at least a stack trace.

**Comment by mrblur** [comment]
Well. I just hit this almost-4-years-old bug and was forced to debug it myself ;)

Simplified stacktrace goes as follows:
1. Doctrine\ORM\EntityManager::flush()
2. Doctrine\ORM\UnitOfWork::commit()
3. Doctrine\ORM\UnitOfWork::executeUpdates()
4. Doctrine\ORM\Event\ListenersInvoker::invoke()
5. Symfony\Bridge\Doctrine\ContainerAwareEventManager::dispatchEvent()
6. Gedmo\Sortable\SortableListener::preUpdate
7. Gedmo\Sortable\SortableListener::persistRelocations
8. Gedmo\Sortable\Mapping\Event\Adapter\ORM::updatePositions

As far as I can tell, the problem comes from changeset itself, as position goes from "anything" to null on removal.
$changeSet in SortableListener::processUpdate (line 234) is nulled already:
```
array:1 [▼
  "order" => array:2 [▼
    0 => 3
    1 => null
  ]
]
```

I am using dynamic form collections (with ```'by_reference' => false```), this happens when first of collection elements is empty. Otherwise, everything is 'working' (see further).
For quick line 279 of SortableListener.php from
```
$newPosition = $changeSet[$config['position']][1];
```
to
```
$newPosition = $changeSet[$config['position']][1];
if (is_null($newPosition)) {
  $newPosition = -1;
}
```

However, patching it this way, changes UnitOfWork from REMOVE to UPDATE on collection entity. It should be removed from collection, as it is "empty". So as far as I can tell, this is not a proper fix. But a place to start ;)

I can't wait for a proper patch, in the meantime I'm forcing my users to manually 'fix' collections by using form validators. And working around with custom javascript.

**Comment by l3pp4rd** [comment]
thanks for the details, now we will be able to create a unit test and patch it properly. So as far as I understand it happens when you a collection with empty item is persisted - with position set to null in general. will need to add a test and fix it, thanks again ;)

**Comment by Padam87** [comment]
As @mrblur commented earlier, the issue is caused by the change set itself. In my case the problem was that I was submitting a symfony form which contained the position field, without the actual value, so it ended up as null, set by the form's property accessor.

**Comment by kappaj** [comment]
I had the same error. I could fix it with setting the default value of the position.

```
    /**
     * @Gedmo\SortablePosition
     * @ORM\Column(name="position", type="integer")
     */
    private $position = 0;
```

**Comment by gmariusze** [comment]
2020 and still not fixed

**Comment by AkenRoberts** [comment]
Terribly sorry about that, I forgot that we're all here to serve you with perfect free software.

**Comment by gmariusze** [comment]
> Terribly sorry about that, I forgot that we're all here to serve you with perfect free software.

Oh, i guess you think you did a good job. My bad, didn't mean to insult your abilities in any way. But seriously, i just noted that as heads up in case people would assume its fixed. Because you know, its normal thing to assume that critical bugs after 8 years are fixed. No need to take it so deep in the tushie.

**Comment by gmariusze** [comment]
> Terribly sorry about that, I forgot that we're all here to serve you with perfect free software.

Oh, i guess you think you did a good job. My bad, didn't mean to insult your abilities in any way. But seriously, i just noted that as heads up in case people would assume its fixed. Because you know, its normal thing to assume that critical bugs after 8 years are fixed. No need to take it so deep in the tushie.

**Comment by svycka** [comment]
@gmariusze you can always create a pull request and it will be fixed if this is a problem for you that's how open source projects work. Otherwise, this won't be fixed for the next 8 years if tasks with higher priority exist unless someone runs into this issue like you and invests some time to fix it.

**Comment by cesaric** [comment]
For what it's worth, I was running into this bug on a SortablePosition & SortableGroup table when I tried directly deleting an entity using **getReference()** or **getPartialReference()**:
```php 
$sortableEntity = EntityManager::getReference($entityName, $identifier);
EntityManager::remove($sortableEntity);  
EntityManager::flush();
```
To get it to work, I had to either run `$entity->getPosition();` before the remove/flush to populate that property with a value from the DB or just do a `EntityManager::find($entityName, $identifier)` instead of a **getReference()** and all worked as normal.
