### ISSUE TITLE
personal translations and sluggable

### ISSUE THREAD

**Issue by iJanki** [doctrine-extensions/DoctrineExtensions#415]
Hello, 

I'm using personal translations and a sluggable field. When I insert a record I get the slug only for default locale. The slug for other locales is not created. 
How is it supposed to work?

Thanks.

**Comment by JHGitty** [comment]
Any updates? https://github.com/stof/StofDoctrineExtensionsBundle/issues/276

**Comment by taylankasap** [comment]
Implementation aside, is there a way (hotfix/workaround) to do it?

**Comment by l3pp4rd** [comment]
doubt that there can be a solution, I do not invest much time in maintaining extensions..

**Comment by lunetics** [comment]
I wish there was a solution for this

**Comment by taylankasap** [comment]
My manual solution: https://gist.github.com/taylankasap/7c2cc1c997bf73c532a4

Of course since this is only a workaround it doesn't do more than what I need. E.g. if you customize the @Gedmo\Sluggable annotation you also need to customize the TranslatableSlugManager.

Usage inside controller goes like this, after flush (both create & update):

```
$this->get('app.doctrine.translatable_slug_manager')->updateTranslations($entity, 'AppBundle:PostTranslation');
```

**Comment by andrewmy** [comment]
@taylankasap your gist is no longer available. Could you post the workaround again? Thanks!

**Comment by taylankasap** [comment]
@andrewmy sorry, I can neither remember this issue nor the project I used that workaround on.
