### ISSUE TITLE
Invalid tree if not flushed regularly

### ISSUE THREAD

**Issue by tero** [doctrine-extensions/DoctrineExtensions#716]
I'm writing migration script which builds tree of existing items and using lot of persistAsFirstChildOf and persistAsNextSiblingOf repository methods. After about 10 items tree will corrupt. It will insert item with left 1, level 2 and right 2 when left should be 13 and right 14. This happens when I'm calling $em-flush() end of the script.

If I call $em->flush() after every persistAsFirstChildOf or persistAsNextSiblingOf tree is build properly.

**Comment by nreynis** [comment]
I have the same issue. It fails to build a very simple three nodes tree:
```php
$repo
    ->persistAsFirstChild($nk)
        ->persistAsFirstChildOf($nl, $nk)
        ->persistAsNextSiblingOf($nm, $nl);
$manager->flush();
```

Results in the following SQL:
```sql
"START TRANSACTION";
INSERT INTO ucn_faq_node (lft, lvl, rgt, id, published, title, created_at, updated_at, root_id, parent_id, node_type) VALUES (0, 0, 0, 244, 1, 'Node K', '2018-06-14 15:51:01', '2018-06-14 15:51:01', NULL, NULL, 'faqroot');
UPDATE ucn_faq_node SET root_id = 244, lvl = 0, lft = 1, rgt = 2 WHERE (id = 244) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
INSERT INTO ucn_faq_node (lft, lvl, rgt, id, published, title, created_at, updated_at, root_id, parent_id, body, node_type) VALUES (0, 0, 0, 246, 1, 'Node M', '2018-06-14 15:51:01', '2018-06-14 15:51:01', NULL, 244, '<p>Lorem ipsum</p>', 'faqresponse');
UPDATE ucn_faq_node SET lft = lft + 2 WHERE (lft >= 1 AND root_id = 244) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
UPDATE ucn_faq_node SET rgt = rgt + 2 WHERE (rgt >= 1 AND root_id = 244) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
UPDATE ucn_faq_node SET root_id = 244, lvl = 1, lft = 1, rgt = 2 WHERE (id = 246) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
INSERT INTO ucn_faq_node (lft, lvl, rgt, id, published, title, created_at, updated_at, root_id, parent_id, node_type) VALUES (0, 0, 0, 245, 1, 'Node L', '2018-06-14 15:51:01', '2018-06-14 15:51:01', NULL, 244, 'faqcategory');
UPDATE ucn_faq_node SET lft = lft + 2 WHERE (lft >= 4 AND root_id = 244) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
UPDATE ucn_faq_node SET rgt = rgt + 2 WHERE (rgt >= 4 AND root_id = 244) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
UPDATE ucn_faq_node SET root_id = 244, lvl = 1, lft = 4, rgt = 5 WHERE (id = 245) AND node_type IN ('faqnode', 'faqcategory', 'faqresponse', 'faqroot');
"COMMIT";
```

Which gives the following nested:

| node | lft | lvl | rgt
|----- | --- | --- | ---
| Node K | 3 | null | 6
| Node L | 4 | 1 | 5
| Node M | 1 | 1 | 2

Instead of:

| node | lft | lvl | rgt
|-------|---|---|---
| Node K | 1 | null | 6
| Node L | 2 | 1 | 3
| Node M | 4 | 1 | 5

@l3pp4rd : do you remember what is the unmerged fix ?

**Comment by l3pp4rd** [comment]
Hi, are you locking your tree when you perform a change in it? see [document](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/transaction-safety.md) if it happens that tree is modified concurrently, it must be locked for other transaction to execute synchronously. I had never got any issues with locking. tree update/delete/insert is not an atomic action if run concurrently

**Comment by nreynis** [comment]
This is not a concurrency issue: I'm running this in a fixture on a single threaded php-fpm instance on my local machine.

I've stepped through the code and I think I know what is going wrong:

My tree is composed of several Entitie types. I'm using inheritance mapping to build a tree with three node types:
* FaqRoot
* FaqCategories
* FaqResponse

All of thoses inherits their tree behaviour from a supermapped entity `FaqNode`.

The issue is that Doctrine's UnitOfWork handle all operations sequentially by entity type:
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L943

Therefore the inserts are not processed in the correct order. It does all the `FaqRoot`, then the `FaqResponse` and last the `FaqCategories`.

**Comment by l3pp4rd** [comment]
Well, in that case it is different, people usually do not use inheritance mapping, it just complicates everything. I do not think it is well supported in extensions in overall. In that case I suggest to do flush whenever you insert a node to the tree. (can do it within transaction to save some overhead). I do not think there can be an easy patch in extension
