### ISSUE TITLE
[Sortable] bulk updates

### ISSUE THREAD

**Issue by till** [doctrine-extensions/DoctrineExtensions#884]
I am trying to wrap my head around how to use the Sortable extension with a bulk update/insert of many entities. Has anyone attempted that? Right now we're persisting entities in a loop, but I don't imagine that is the best solution?

Do you guys have any pointers?

**Comment by AndreasA** [comment]
I also tried it lately and the issue is the bulk combination of inserts and updates, so when using a child-relation and re-ordering a log of entities in it and adding some, so e.g. in my case I am using an importer from an external system which means I have to re-order all the child relations. 
Therefore, I clear the existing ArrayCollection and add all entities to it again in the correct order with `position = -1`. 
The relation is set to `orphanRemoval = true` and `cascade = persist`. In order to avoid possible unique key exceptions (as I am not flushing on each removal), I am updating and inserting data (and not re-adding data if I want to remove it which is taken care of by orphanRemoval). 
The related table is basically a M:N table with additional fields.

Now the problem is that due https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/lib/Gedmo/Sortable/SortableListener.php#L87

The updates are always processed first and then the inserts which results in inserts always being after the updates, although in the collection the updates are later. 
I guess the same would be an issue when doing persist manually.

Not sure, though, if there is a good workaround or a better solution on how to handle position updates?
